{
  "hash": "8a91fb3dbb4497b98ecaf586d1c222a3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hồi quy tuyến tính sử dụng R\"\nauthor: \"Ba Khuong Cao - caobakhuongytcc@gmail.com\"\nformat:\n  pdf:\n    toc: true\n    toc-depth: 2         \nexecute:\n  eval: true\n  echo: true\n  warning: false\n  message: false\n---\n\\newpage\n::: callout-important\n## Những giả định (`Assumptions`) của mô hình hồi quy tuyến tính(`Linear least squares regression model`).\nMô hình hồi quy tuyến tính thường phải thỏa mãn **đồng thời** một số giả định (LINE), bao gồm:\n\n- **L**inear relationship: Có mối tương quan tuyến tính giữa biến độc lập và biến phụ thuộc\n\n- **I**ndependent of errors: Các quan sát độc lập với nhau. \n\n- **N**ormal distribution of residuals: Phần dư (`residuals`) có phân phối `normal`\n\n- **E**quivalent of variance: Phương sai bằng nhau.\n:::\n\n\n::: callout-note\n## Các bước thực hiện\n\n1.  Loading packages, dataset\n2.  Khảo sát mối tương quan giữa biến phụ thuộc và biến độc lập\n3.  Xây dựng mô hình\n4.  Xem xét các giả định\n5. Làm gì khi giả định không được thỏa mãn\n:::\n\n# 1. Loading packages, dataset\n## Loading packages\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check whether pacman is available and install if needed\noptions(repos = c(CRAN = \"https://cloud.r-project.org\"))\nif (!requireNamespace(\"pacman\", quietly = TRUE)) install.packages(\"pacman\")\n\n# Use pacman to install (if needed) and load the required packages\npacman::p_load(ggplot2,patchwork)\n```\n:::\n\n\n## Loading dataset\n\nChúng ta có thể load dataset này vào R để phân tích:\n\n\n::: {.cell}\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(epistat2024)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"v001\"            \"area\"            \"sex\"             \"status\"         \n [5] \"statusage\"       \"year5\"           \"age5\"            \"exactage5\"      \n [9] \"height5\"         \"weight5\"         \"fev5\"            \"vc5\"            \n[13] \"fevpp5\"          \"vcpp5\"           \"threshold5\"      \"fevafter5\"      \n[17] \"slope5\"          \"cough5\"          \"phlegm5\"         \"bronch5\"        \n[21] \"dyspnea5\"        \"wheeze5\"         \"asthma5\"         \"smokhabits5\"    \n[25] \"smoking5\"        \"toteos5\"         \"pets5\"           \"pets_type5\"     \n[29] \"cooking5\"        \"house5\"          \"occup_exposure5\" \"year8\"          \n[33] \"age8\"            \"exactage8\"       \"height8\"         \"weight8\"        \n[37] \"fev8\"            \"vc8\"             \"fevpp8\"          \"vcpp8\"          \n[41] \"threshold8\"      \"fevafter8\"       \"slope8\"          \"cough8\"         \n[45] \"phlegm8\"         \"bronch8\"         \"dyspnea8\"        \"wheeze8\"        \n[49] \"asthma8\"         \"smokhabits8\"     \"smoking8\"        \"toteos8\"        \n[53] \"pets8\"           \"pets_type8\"      \"cooking8\"        \"house8\"         \n[57] \"occup_exposure8\" \"year9\"           \"age9\"            \"exactage9\"      \n[61] \"height9\"         \"weight9\"         \"fev9\"            \"vc9\"            \n[65] \"fevpp9\"          \"vcpp9\"           \"threshold9\"      \"fevafter9\"      \n[69] \"slope9\"          \"cough9\"          \"phlegm9\"         \"bronch9\"        \n[73] \"dyspnea9\"        \"wheeze9\"         \"asthma9\"         \"smokhabits9\"    \n[77] \"smoking9\"        \"toteos9\"         \"ige9\"            \"pets9\"          \n[81] \"pets_type9\"      \"cooking9\"        \"house9\"          \"occup_exposure9\"\n[85] \"wheal1\"          \"wheal2\"          \"wheal3\"          \"wheal4\"         \n[89] \"wheal5\"          \"wheal6\"          \"wheal7\"          \"wheal8\"         \n```\n\n\n:::\n:::\n\n# 2. Khảo sát mối tương quan giữa biến phụ thuộc và biến độc lập\n## scatterplot of VC at visit 9 (VC9) and height at visit 9 (height9). \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(epistat2024, aes(x = height9, y = vc9, colour = height9)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) + # regression line\n  labs(title = \"Scatterplot of VC vs Height at Visit 9\",\n       x = \"Height at Visit 9\",\n       y = \"VC at Visit 9\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Day_2_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n# P-P plots\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sort data and compute CDFs\nvc9_sorted <- sort(epistat2024$vc9)\ndf_pp <- data.frame(\n  empirical = ppoints(length(vc9_sorted)),\n  theoretical = pnorm(vc9_sorted, mean = mean(vc9_sorted, na.rm = TRUE),\n                      sd = sd(vc9_sorted, na.rm = TRUE))\n)\n\nggplot(df_pp, aes(x = theoretical, y = empirical)) +\n  geom_point(shape = 1, size = 0.5) +  # hollow circle\n  geom_abline(intercept = 0, slope = 1, color = \"red\", linetype = \"dashed\") +\n  labs(title = \"P-P Plot of VC9\", x = \"Theoretical\", y = \"Empirical\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Day_2_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheight9_sorted <- sort(epistat2024$height9)\ndf_pp_height <- data.frame(\n  empirical = ppoints(length(height9_sorted)),\n  theoretical = pnorm(height9_sorted, mean = mean(height9_sorted, na.rm = TRUE),\n                      sd = sd(height9_sorted, na.rm = TRUE))\n)\n\n\nggplot(df_pp_height, aes(x = theoretical, y = empirical)) +\n  geom_point(shape = 1, size = 0.5) +  # hollow circle\n  geom_abline(intercept = 0, slope = 1, color = \"red\", linetype = \"dashed\") +\n  labs(title = \"P-P Plot of Height9\", x = \"Theoretical\", y = \"Empirical\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Day_2_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::{.callout-note}\nBased on the scatterplot the relation looks linear. The P-P plots of VC9 and HEIGHT9 indicate that both variables are normally distributed. So a Pearson correlation coefficient can be calculated.\n:::\n\n\n## Calculate the correct correlationcoefficient (Pearson or Spearman).\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Pearson correlation test\ncor_test <- cor.test(epistat2024$vc9, epistat2024$height9, method = \"pearson\")\n\n# Extract correlation coefficient\nr <- cor_test$estimate\n\n# % explained variance (R-squared)\nexplained_variance <- r^2 * 100\n\n# Extract p-value\np_value <- cor_test$p.value\n\n# Print results\ncat(\"Pearson correlation r =\", round(r, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPearson correlation r = 0.787 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Explained variance R² =\", round(explained_variance, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExplained variance R² = 61.98 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p-value =\", p_value, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value = 0 \n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- cor(epistat2024$vc9, epistat2024$height9, use = \"complete.obs\")\nexplained_variance <- r^2 * 100\n\nggplot(epistat2024, aes(x = height9, y = vc9)) +\n  geom_point(shape = 1, size = 2) +           # hollow circles\n  geom_smooth(method = \"lm\", color = \"red\", se = FALSE) +  # regression line\n  labs(title = paste0(\"VC9 vs Height9 (R² = \", round(explained_variance, 2), \"%)\"),\n       x = \"Height at Visit 9\",\n       y = \"VC at Visit 9\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Day_2_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::{.callout-note}\nThe correlation coefficient is 0.787 which is ‘strong’. The p-value is 0.000 which is lower than 0.05 and significant. The % explained variance is 0.787^2 = 0.6198. So 61.98% of the variance in VC can be explained by height.\n:::\n\n# 3. Xây dựng mô hình hồi quy tuyến tính\n## Estimate the effect of height9 on VC9 with the help of a linear regression analysis\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression: VC9 ~ height9\nmodel <- lm(vc9 ~ height9, data = epistat2024)\nresiduals_model <- residuals(model)\nfitted_model <- fitted(model)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = vc9 ~ height9, data = epistat2024)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-229.320  -38.345    0.049   38.819  271.221 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1024.7299    22.3942  -45.76   <2e-16 ***\nheight9         8.2787     0.1312   63.12   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 60 on 2444 degrees of freedom\n  (1757 observations deleted due to missingness)\nMultiple R-squared:  0.6198,\tAdjusted R-squared:  0.6196 \nF-statistic:  3984 on 1 and 2444 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 95% confidence intervals\nconfint(model, level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   2.5 %      97.5 %\n(Intercept) -1068.643537 -980.816275\nheight9         8.021501    8.535889\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\nMagnitude of height on VC: This is actually the regression coefficient. So 8.279. For each cm higher height the VC is predicted to be 8.279 cl higher\nThe effect has a p-value of 0.000 and is thus significantly different from 0. The 95% CI can be calculated by 8.279 ± 1.96 * 0.131. The 95% CI is 8.022 - 8.536\n\n:::\n# 4. Xem xét các giả định\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model, which = 1)  # Residuals vs Fitted\n```\n\n::: {.cell-output-display}\n![](Day_2_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model, which = 2)  # Normal Q-Q plot\n```\n\n::: {.cell-output-display}\n![](Day_2_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|warning: false\nggplot(data.frame(residuals = residuals_model), aes(x = residuals)) +\n  geom_histogram(aes(y = ..density..), binwidth = 1, fill = \"lightblue\", color = \"black\") +\n  stat_function(fun = dnorm, args = list(mean = mean(residuals_model), sd = sd(residuals_model)),\n                color = \"red\", size = 1) +\n  labs(title = \"Histogram of Residuals with Normal Curve\", x = \"Residuals\", y = \"Density\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Day_2_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(data.frame(residuals = residuals_model), aes(x = residuals)) +\n  geom_histogram(aes(y = ..density..), binwidth = 1, fill = \"lightblue\", color = \"black\") +\n  stat_function(fun = dnorm, args = list(mean = mean(residuals_model), sd = sd(residuals_model)),\n                color = \"red\", size = 1) +\n  labs(title = \"Histogram of Residuals\", x = \"Residuals\", y = \"Density\") +\n  theme_minimal()\n\np2 <- ggplot(data.frame(residuals = residuals_model), aes(sample = residuals)) +\n  stat_qq(shape = 1, color = \"blue\") +\n  stat_qq_line(color = \"red\") +\n  labs(title = \"Q-Q Plot of Residuals\") +\n  theme_minimal()\n\np3 <- ggplot(data.frame(fitted = fitted_model, residuals = residuals_model), aes(x = fitted, y = residuals)) +\n  geom_point(shape = 1, color = \"blue\") +\n  geom_hline(yintercept = 0, color = \"red\", linetype = \"dashed\") +\n  labs(title = \"Residuals vs Fitted\", x = \"Fitted values\", y = \"Residuals\") +\n  theme_minimal()\n\ncombined_plot <- (p1 | p2) / p3\ncombined_plot\n```\n\n::: {.cell-output-display}\n![](Day_2_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n# 5. Làm gì khi giả định không được thỏa mãn\n* Một giả định cần đặc biệt lưu ý đó là các quan sát không độc lập với nhau: \n  - Ví dụ, trong đo lường lặp lại: Cân nặng của trẻ được đo lường nhiều lần trong một một năm đầu đời.Như vậy,các đo lường cân nặng của cùng một trẻ thường có mối tương quan nội tại với nhau.\n  \n  - Một ví dụ khác mà chúng ta thường không chú ý đến: chúng ta đo lường tại nhiều bệnh viện/địa điểm khác nhau. Khi đó, việc các kết quả quan sát/đo tại cùng một bệnh viện/địa điểm có mối tương quan nội tại với nhau.\n  \n  - Nghiên cứu chọn mẫu nhiều giai đoạn, lấy ngẫu nhiên một số xã ở một vài tỉnh, từ đó lấy ngẫu nhiên một vài thôn/bản ở xã, và chọn ngẫu nhiên/không ngẫu nhiên đối tượng nghiên cứu tại thôn/bản được chọn. Như vậy, dữ liệu thu được sẽ có nhiều cấp (multi levels) và các đo lường tại cùng một thôn/bản/tổ có thể có mối tương quan nội tại(ICC) với nhau (có thể lớn hoặc nhỏ hơn).\n\nThực tế thì không có điểm cắt chính xác nào để nói ICC đó là \"đủ nhỏ\" để bỏ qua nó. Tuy nhiên một số statisticians nôm na nói về con số 0.1-0.2. Khi giả định các quan sát độc lập với nhau không được thỏa mãn thì một giải pháp đó là áp dụng multilevel analysis (mixed model). Quá trình thực hiện phương pháp phần tích này có phần phức tạp hơn và sẽ được trình bày trong một bài viết khác.\n  \n",
    "supporting": [
      "Day_2_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}